# Generated by Django 3.0.5 on 2020-04-17 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('native_name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('phrase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='translations.Phrase')),
                ('special_note', models.TextField(blank=True, verbose_name='Special note to doctor (if needed)')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.Language')),
            ],
            bases=('translations.phrase',),
        ),
    ]
