# Generated by Django 3.0.5 on 2020-04-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('language', 'phrase')},
        ),
    ]
