# Generated by Django 3.0.5 on 2020-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_auto_20200417_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='audio_clip',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
