# Generated by Django 3.0.5 on 2020-04-17 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
