# Generated by Django 3.0.5 on 2020-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0007_auto_20200418_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='volunteer',
            name='preferred_days',
            field=models.ManyToManyField(blank=True, to='translations.DayOfWeek'),
        ),
    ]
