# Generated by Django 3.0.5 on 2020-04-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0012_auto_20200419_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='audio_clip',
            field=models.FileField(blank=True, help_text='Optional, will be auto generated if not provided.', upload_to='recorded_clips/'),
        ),
    ]
