# Generated by Django 3.0.5 on 2020-04-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0013_auto_20200419_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='speaking_rate',
            field=models.DecimalField(decimal_places=2, default=0.85, max_digits=3),
        ),
        migrations.AlterField(
            model_name='translation',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
