# Generated by Django 3.0.5 on 2020-04-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0014_auto_20200419_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phrase',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='phrase',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
