# Generated by Django 3.0.5 on 2020-04-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0016_populate_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
