# Generated by Django 3.0.5 on 2020-04-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0018_auto_20200420_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='availability_slots',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='language',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
