# Generated by Django 3.0.5 on 2020-04-21 08:09

from django.db import migrations


def add_doctor_user_type(apps, schema_editor):
    UserType = apps.get_model('translations', 'UserType')
    return UserType.objects.create(name='Doctor')


def populate_user_type(apps, schema_editor):
    Category = apps.get_model('translations', 'Category')
    doctor = add_doctor_user_type(apps, schema_editor)

    for category in Category.objects.all():
        category.intended_for.add(doctor)


class Migration(migrations.Migration):
    dependencies = [
        ('translations', '0022_auto_20200421_1608'),
    ]

    operations = [
        migrations.RunPython(populate_user_type)
    ]
