# Generated by Django 3.0.5 on 2020-04-21 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0023_populate_categories_with_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertype',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='usertype',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PhraseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.Category')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.Phrase')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='phrase',
            name='categories',
            field=models.ManyToManyField(related_name='cat', related_query_name='phrases', through='translations.PhraseCategory', to='translations.Category'),
        ),
    ]
