# Generated by Django 3.0.5 on 2020-04-21 11:08

from django.db import migrations


def move_category_m2m(apps, schema_editor):
    Category = apps.get_model('translations', 'Category')
    Phrase = apps.get_model('translations', 'Phrase')

    for category in Category.objects.all():
        for phrase in Phrase.objects.filter(category=category):
            phrase.categories.add(category)


class Migration(migrations.Migration):
    dependencies = [
        ('translations', '0024_auto_20200421_1908'),
    ]

    operations = [
        migrations.RunPython(move_category_m2m)
    ]
