# Generated by Django 3.0.5 on 2020-04-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0025_move_category_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='category',
        ),
        migrations.AlterField(
            model_name='usertype',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
