# Generated by Django 3.0.5 on 2020-04-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0030_usertype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='needs_original_phrase',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='usertype',
            name='needs_original_phrase',
            field=models.NullBooleanField(),
        ),
    ]
