# Generated by Django 3.0.5 on 2020-04-22 06:07

from django.db import migrations


def copy_ordering(apps, schema_editor):
    Category = apps.get_model('translations', 'Category')

    from django.db.models import F
    Category.objects.all().update(
        order=F('id')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0032_auto_20200422_1404'),
    ]

    operations = [
        migrations.RunPython(copy_ordering)
    ]
