# Generated by Django 3.0.5 on 2020-04-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0033_populate_ordering_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='speech_code',
            field=models.CharField(blank=True, db_index=True, help_text='Speech will not be generated if blank', max_length=10),
        ),
        migrations.AddField(
            model_name='language',
            name='translation_code',
            field=models.CharField(blank=True, db_index=True, help_text='Translation will not be generated if blank', max_length=10),
        ),
    ]
