# Generated by Django 3.0.5 on 2020-04-23 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0034_auto_20200423_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('whats_wrong', models.TextField(blank=True)),
                ('suggestion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.Translation')),
            ],
        ),
    ]
