# Generated by Django 3.0.5 on 2020-04-24 12:24

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0036_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationfeedback',
            name='status',
            field=django_fsm.FSMField(default='new', max_length=50, protected=True),
        ),
    ]
