# Generated by Django 3.0.5 on 2020-04-27 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0040_auto_20200427_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadable',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.Category'),
        ),
    ]
