# Generated by Django 3.0.5 on 2020-04-29 13:29

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import translations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0042_translation_romanized'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='google_sheet_id',
            field=models.CharField(blank=True, max_length=50, validators=[translations.validators.validate_google_sheet_id]),
        ),
        migrations.CreateModel(
            name='TranslationImportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheet_id', models.CharField(max_length=50)),
                ('status', django_fsm.FSMField(default='New', max_length=50)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.Language')),
            ],
        ),
    ]
