# Generated by Django 3.0.5 on 2020-04-29 15:03

from django.db import migrations, models
import translations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0043_auto_20200429_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='google_sheet_id',
            field=models.CharField(blank=True, max_length=50, validators=[translations.validators.validate_google_sheet_id], verbose_name='Google Sheet ID'),
        ),
    ]
